# syntax version.

services:
  # API service
  delightful-service:
    image: ghcr.io/saashqdev/delightful/delightful-service:${DELIGHTFUL_SERVICE_TAG-latest}
    platform: ${PLATFORM}
    container_name: delightful-service
    #restart: always
    environment:
      type: main
      suffix: -open
      CRONTAB_ENABLE: "false"
    ports:
      - "9501:9501"
      - "9502:9502"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    volumes:
      - ./volumes/storage/files:/opt/www/storage/files
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 4G
    networks:
      - delightful-sandbox-network

  delightful-service-daemon:
    image: ghcr.io/saashqdev/delightful/delightful-service:${DELIGHTFUL_SERVICE_TAG-latest}
    platform: ${PLATFORM}
    container_name: delightful-service-daemon
    #restart: always
    environment:
      type: daemon
      suffix: -daemon
      CRONTAB_ENABLE: "true"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      delightful-service:
        condition: service_started
    volumes:
       - ./volumes/storage/files:/opt/www/storage/files
       - ./bin/delightful-service/daemon-entrypoint.sh:/opt/www/start.sh
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 4G
    networks:
      - delightful-sandbox-network


  # Web application
  delightful-web:
    image: ghcr.io/saashqdev/delightful/delightful-web:${DELIGHTFUL_WEB_TAG-latest}
    container_name: delightful-web
    #restart: always
    environment:
      DELIGHTFUL_SOCKET_BASE_URL: ${DELIGHTFUL_SOCKET_BASE_URL}
      DELIGHTFUL_SERVICE_BASE_URL: ${DELIGHTFUL_SERVICE_BASE_URL}
      DELIGHTFUL_EDITION: ${DELIGHTFUL_EDITION}
    ports:
      - "8080:8080"
    # volumes:
    #   - ./web:/app
    env_file:
      - .env
    networks:
      - delightful-sandbox-network

  # Be Delightful service
  be-delightful:
    image: ghcr.io/saashqdev/delightful/be-delightful:${BE_DELIGHTFUL_TAG-latest}
    container_name: be-delightful
    #restart: always
    profiles:
      - be-delightful
    ports:
      - "8002:8002"
    volumes:
      - ./volumes/storage/files:/opt/www/storage/files
      - ./config/config.yaml:/app/config/config.yaml
    env_file:
      - config/.env_be_delightful
    networks:
      - delightful-sandbox-network

  # Delightful gateway service
  delightful-gateway:
    image: ghcr.io/saashqdev/delightful/delightful-gateway:${DELIGHTFUL_GATEWAY_TAG-latest}
    container_name: delightful-gateway
    #restart: always
    profiles:
      - delightful-gateway
    ports:
      - "8001:8001"
    depends_on:
      redis:
        condition: service_started
    volumes:
      - ./config/.env_delightful_gateway:/app/.env
    env_file:
      - config/.env_delightful_gateway
    networks:
      - delightful-sandbox-network

  # Sandbox gateway service
  sandbox-gateway:
    image: ghcr.io/saashqdev/delightful/sandbox-gateway:${SANDBOX_GATEWAY_TAG-latest}
    container_name: sandbox-gateway
    #restart: always
    profiles:
      - sandbox-gateway
    environment:
      BE_DELIGHTFUL_CONFIG_FILE_PATH: ${BE_DELIGHTFUL_CONFIG_FILE_PATH:-${PWD}/config/config.yaml}
    depends_on:
      qdrant:
        condition: service_started
      delightful-gateway:
        condition: service_started
    ports:
      - "39003:39003"
    volumes:
      - ./config/.env_be_delightful:/app/.env.agent
      - ${SANDBOX_DOCKER_RUNTIME}:/var/run/docker.sock
      - ./config/config.yaml:/app/config/config.yaml
    env_file:
      - config/.env_sandbox_gateway
    networks:
      - delightful-sandbox-network

 # Caddy file service
  caddy:
    image: caddy:2.7-alpine
    container_name: delightful-caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/storage/files:/srv/files
      - ./bin/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./volumes/caddy/data:/data
      - ./volumes/caddy/config:/config
    command: caddy run --config /etc/caddy/Caddyfile
    networks:
      - delightful-sandbox-network

  # MySQL database service
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./volumes/db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
    env_file:
      - .env
    networks:
      - delightful-sandbox-network

  # Redis cache service
  redis:
    image: redis:6-alpine
    container_name: delightful-redis
    restart: always
    environment:
      REDISCLI_AUTH: ${REDIS_PASSWORD}
    volumes:
      - ./volumes/redis/data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
    env_file:
      - .env
    networks:
      - delightful-sandbox-network


  # RabbitMQ message queue service
  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    container_name: delightful-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${AMQP_USER}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${AMQP_VHOST}
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management console port
    volumes:
      - ./volumes/rabbitmq/data:/var/lib/rabbitmq
      - ./volumes/rabbitmq/logs:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env
    networks:
      - delightful-sandbox-network


  # OpenSearch search engine service
  # opensearch:
  #   container_name: delightful-opensearch
  #   image: opensearchproject/opensearch:latest
  #   restart: always
  #   profiles:
  #     - opensearch
  #   environment:
  #     discovery.type: ${OPENSEARCH_DISCOVERY_TYPE}
  #     bootstrap.memory_lock: ${OPENSEARCH_BOOTSTRAP_MEMORY_LOCK}
  #     OPENSEARCH_JAVA_OPTS: -Xms${OPENSEARCH_JAVA_OPTS_MIN} -Xmx${OPENSEARCH_JAVA_OPTS_MAX}
  #     OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
  #   ulimits:
  #     memlock:
  #       soft: ${OPENSEARCH_MEMLOCK_SOFT}
  #       hard: ${OPENSEARCH_MEMLOCK_HARD}
  #     nofile:
  #       soft: ${OPENSEARCH_NOFILE_SOFT}
  #       hard: ${OPENSEARCH_NOFILE_HARD}
  #   volumes:
  #     - ./volumes/opensearch/data:/usr/share/opensearch/data
  #   networks:
  #     - default
  #     - opensearch-net
  #   env_file:
  #     - .env

  # OpenSearch Dashboards UI
  # opensearch-dashboards:
  #   container_name: delightful-opensearch-dashboards
  #   image: opensearchproject/opensearch-dashboards:latest
  #   restart: always
  #   profiles:
  #     - opensearch-dashboards
  #   environment:
  #     OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
  #   volumes:
  #     - ./volumes/opensearch/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
  #   networks:
  #     - default
  #     - opensearch-net
  #   depends_on:
  #     - opensearch
  #   env_file:
  #     - .env

  # Qdrant vector database service
  qdrant:
    image: qdrant/qdrant:latest
    container_name: delightful-qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"  # GRPC
    volumes:
      - ./volumes/qdrant:/qdrant/storage
    environment:
      QDRANT_API_KEY: ${ODIN_QDRANT_API_KEY}
    env_file:
      - .env
    networks:
      - delightful-sandbox-network

networks:
  delightful-sandbox-network:
    external: true
    driver: bridge
