services:
  # API Gateway Service - Go version
  magic-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway-${ENV:-dev}
    ports:
      - "${DELIGHTFUL_GATEWAY_PORT}:${DELIGHTFUL_GATEWAY_PORT}"
    volumes:
      - ./config/${ENV:-dev}/.env:/app/.env
    restart: unless-stopped
    networks:
      - magic-sandbox-network
    # depends_on:
    #   - magic-redis

  # Redis service
  magic-redis:
    image: public.ecr.aws/docker/library/redis:alpine
    container_name: api-gateway-redis
    volumes:
      - ./redis_data:/data
    restart: unless-stopped
    networks:
      - magic-sandbox-network
    command: redis-server --appendonly yes
    labels:
      - "com.docker.compose.skip.create=true"

volumes:
  caddy_data:
  caddy_config:

networks:
  magic-sandbox-network:
    external: true
    driver: bridge
